export class MedicalConsts {
  static degrees = [
    {key: 'Student', value: 'Student'},
    {key: 'Lek', value: 'lek.'},
    {key: 'LekDent', value: 'lek. dent.'},
    {key: 'Spec', value: 'lek. spec.'},
    {key: 'Dr', value: 'Dr n. med.'},
    {key: 'DrHab', value: 'Dr hab. n. med'},
  ]

  static specializations = [
    {key: 'Alergologia', value: 'Alergologia'},
    {key: 'AnestezjologiaIIntensywnaTerapia', value: 'Anestezjologi i intensywna terapia'},
    {key: 'Angiologia', value: 'Angiologia'},
    {key: 'ChorobyPluc', value: 'Choroby Płuc'},
    {key: 'AudiologiaIFoniatria', value: 'Audiologia i Foniatria'},
    {key: 'ChorobyZakazne', value: 'Choroby zakaźne'},
    {key: 'ChirurgiaDziecieca', value: 'Chirurgia dziecięca'},
    {key: 'ChirurgiaOgolna', value: 'Chirurgia ogólna'},
    {key: 'ChirurgiaPlastyczna', value: 'Chirurgia plastyczna'},
    {key: 'ChirurgiaOnkologiczna', value: 'Chirurgia onkologiczna'},
    {key: 'ChirurgiaSzczekowoTwarzowa', value: 'Chirurgia szczekowo twarzowa'},
    {key: 'Endokrynologia', value: 'Endokrynologia'},
    {key: 'Epidemiologia', value: 'Epidemiologia'},
    {key: 'Geriatria', value: 'Geriatria'},
    {key: 'Hematologia', value: 'Hematologia'},
    {key: 'IntensywnaTerapia', value: 'Intensywna terapia'},
    {key: 'Kardiologia', value: 'Kardiologia'},
    {key: 'MedycynaRodzinna', value: 'Medycyna rodzinna'},
    {key: 'Neurologia', value: 'Neurologia'},
    {key: 'Okulistyka', value: 'Okulistyka'},
    {key: 'OnkologiaKliniczna', value: 'Onkologia kliniczna'},
    {key: 'Pediatria', value: 'Pediatria'},
    {key: 'PediatriaMetaboliczna', value: 'Pediatria Metaboliczna'},
    {key: 'PoloznictwoIGinekologia', value: 'Poloznictwo i ginekologia'},
    {key: 'Psychiatria', value: 'Psychiatria'},
    {key: 'Reumatologia', value: 'Reumatologia'},
    {key: 'Seksuologia', value: 'Seksuologia'},
    {key: 'Urologia', value: 'Urologia'},
    {key: 'ZdrowiePubliczne', value: 'Zdrowie publiczne'},
  ]
}